# Generated by Django 4.0.4 on 2022-04-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='emailaddress',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phonenum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='fullname',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
