# Generated by Django 4.0.4 on 2022-04-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_blog_tempuser_post_likes_alter_post_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='user_likse', to='landing.tempuser'),
        ),
    ]
