# Generated by Django 4.0.4 on 2022-04-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked_users',
        ),
    ]
